language: node_js
sudo: false
branches:
  except:
    - develop
script: npm i -g mkdoc && mk install && mk cover && npm run report
node_js:
  - '6.1.0'
  - stable
after_success:
  - npm run coveralls
